config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'home#index'

  resources :memorandums
  resources :others


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memorandum.rb
# == Schema Information
#
# Table name: memorandums
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  private    :boolean          default(FALSE)
#  source     :string           default("")
#  tag        :string           default("Uncategorized")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_memorandums_on_user_id  (user_id)
#
class Memorandum < ApplicationRecord
    validates :content, presence: true
    validates :tag, presence: true
    belongs_to :user

    def create_time
        created_at.strftime('%Y/%m/%d')
    end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :memorandums
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!
    def index
        randoms = current_user.memorandums
        @random = randoms.sample
    end

end

app/controllers/memorandums_controller.rb
class MemorandumsController < ApplicationController
    before_action :authenticate_user!
    def index
        @memorandums = current_user.memorandums
    end


    def show
        randoms = current_user.memorandums
        @random = randoms.sample
        render json: @random
    end

    def new
        @memorandum = current_user.memorandums.build
    end

    def create
        @memorandum = current_user.memorandums.build(memorandum_params)
        if @memorandum.save
            redirect_to root_path ,notice: '登録完了'
        else
            flash.now[:error] = '失敗しました'
            render :new
        end
    end

    def edit
        @memorandum = current_user.memorandums.find(params[:id])
    end

    def update
        @memorandum = current_user.memorandums.find(params[:id])
        if @memorandum.update(memorandum_params)
            redirect_to root_path, notice: '更新完了'
        else
            flash.now[:error] = '更新に失敗しました'
            render :edit
        end
    end

    def destroy
        memorandum = current_user.memorandums.find(params[:id])
        memorandum.destroy!
        redirect_to memorandums_path ,notice: '削除完了'
    end

    private
    def memorandum_params
        params.require(:memorandum).permit(:content, :tag, :source, :private)
    end
end

app/controllers/others_controller.rb
class OthersController < ApplicationController
    before_action :authenticate_user!
    def index
        memorandums = Memorandum.where(private: false)
        @memorandums = memorandums.order(id: "desc").limit(50)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/commons/_header.html.haml
.header
    .container
        .header-title
            MEMORAND
            %span<>
                O
            M
        .header-description 登録したメモをランダムに表示します！
.flex-wrapper.header-buttons
    - unless current_page?(root_path)
        =link_to root_path do
            %button.header-button.home-button BACK
    - else
        =link_to others_path do
            %button.header-button.others-button Others
            
    - if user_signed_in?
        =link_to destroy_user_session_path, data: {method: 'delete'}  do
            %button.header-button Logout
    - else 
        =link_to new_user_session_path do
            %button.header-button Login
    

app/views/home/index.html.haml
=render 'commons/header'

.home-wrapper

    .phrase-show
        .phrase-show-content#phrase-content-area
            -unless @random.nil?    
                = @random&.content
            -else
                まだ何も登録されていません！
            
        .phrase-show-info#phrase-info-area
            = @random&.source
            = @random&.tag

    .home-buttons
        %button.home-buttons-item#next-memorandum
            次のメモを見る
        
        %button.home-buttons-item
            =link_to '新しいメモを登録する' ,new_memorandum_path
        
        %button.home-buttons-item
            =link_to 'メモ一覧を見る' ,memorandums_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title MemoRandom
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body

    .container        
      - if flash[:notice]
        .alert.alert-info
          = flash[:notice]
      - if flash[:alert]
        .alert.alert-danger
          = flash[:alert]
    = yield

    .footer
      (c)funAholi9

app/views/memorandums/edit.html.haml
=render 'commons/header'

%ul
    - @memorandum.errors.full_messages.each do |message|
        %li= message

.container
    %h1.page-title
        Edit Memorandum

    = form_with(model: @memorandum, local: true) do |f|
        .form-label
            = f.label :content, 'Memorandum'
        .form-area
            = f.text_area :content, class:""
        .flex-wrapper
            .tag-wrapper.flex-wrapper
                .form-label
                    = f.label :tag, 'Tag'
                .form-field
                    = f.text_field :tag
            .source-wrapper.flex-wrapper
                .form-label
                    = f.label :source, 'Source'
                .form-field
                    = f.text_field :source
        .actions
            = f.submit "UPDATE", class: "button"

app/views/memorandums/index.html.haml
=render 'commons/header'

.container.align-center
    %h1.page-title Index
    .table-wrapper
        %table.table
            %tr
                %th Time
                %th Content
                %th Tag
                %th Source
                %th Edit
            -@memorandums.each do |memorandum|
                %tr
                    %td=memorandum.created_at.strftime('%Y/%m/%d')
                    %td=memorandum.content
                    %td=memorandum.tag
                    %td=memorandum.source
                    %td.edit
                        =link_to 'edit', edit_memorandum_path(memorandum)
                        %br
                        =link_to 'delete', memorandum_path(memorandum) , data: { method: 'delete' , confirm: '本当に削除しますか？'}

        %div
            　
        

app/views/memorandums/new.html.haml
=render 'commons/header'

%ul
    - @memorandum.errors.full_messages.each do |message|
        %li= message

.container
    %h1.page-title
        Create New Memorandum

    = form_with(model: @memorandum, local: true) do |f|
        .form-label
            = f.label :content, 'Memorandum'
        .form-area
            = f.text_area :content, class:""
        .flex-wrapper
            .tag-wrapper.flex-wrapper
                .form-label
                    = f.label :tag, 'Tag'
                .form-field
                    = f.text_field :tag
            .source-wrapper.flex-wrapper
                .form-label
                    = f.label :source, 'Source'
                .form-field
                    = f.text_field :source
        .check-box-wrapper
            .form-label
                = f.label :private
                = f.check_box :private
        .actions
            = f.submit "CREATE", class: "button"

app/views/others/index.html.haml
=render 'commons/header'

.container.align-center
    %h1.page-title みんなのメモ

    .align-left
        -@memorandums.each do |memorandum|
            .others-memo
                %p
                    =memorandum.content
            